apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: extract-version-pom
spec:
  results:
    - name: app-version
      type: string
      description: The current app version
  params:
    - name: context
      description: "working dir"
      default: "."
  workspaces:
    - name: source
  steps:
   - name: get-version
     image: gcr.io/cloud-builders/mvn
     script: |
      pwd
      echo $(workspaces.source.path)
      echo $(params.context)
      cd $(workspaces.source.path)/$(params.context)
      pwd
      ls
      mvn help:evaluate -Dexpression=project.version -q -DforceStdout
      APP_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
      echo $APP_VERSION
      BUILD_DATE=$(date +'%Y%m%d%H%M')
      echo $BUILD_DATE
      VERSION=$APP_VERSION-$BUILD_DATE
      echo $VERSION
      echo -n $VERSION | tee $(results.app-version.path)
