apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: extract-version-pom
spec:
  results:
    - name: app-version
      type: string
      description: The current app version
  params:
    - name: context
      description: "working dir"
      default: "."
  workspaces:
    - name: source
  steps:
   - name: get-version
     image: registry.access.redhat.com/ubi8/openjdk-17:1.15-1.1679485273
     script: |
      pwd
      echo $(workspaces.source.path)
      echo $(params.context)
      cd $(workspaces.source.path)/$(params.context)
      pwd
      ls
      mvn -fn help:evaluate -Dexpression=project.version -q -DforceStdout
      APP_VERSION=$(mvn -fn help:evaluate -Dexpression=project.version -q -DforceStdout)
      echo $APP_VERSION
      BUILD_DATE=$(date +'%Y%m%d%H%M')
      echo $BUILD_DATE
      VERSION=$APP_VERSION-$BUILD_DATE
      echo $VERSION
      echo -n $VERSION | tee $(results.app-version.path)
