apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: event-listener-github
spec:
  serviceAccountName: pipeline
  triggers:
  - bindings:
    - ref: github-push
    - ref: kafka-producer
    template:
      ref: trigger-template-github