apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: gogs-event-listener
spec:
  serviceAccountName: pipeline
  triggers:
  - bindings:
    - ref: gogs-push
    template:
      ref: gogs-trigger-template