apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: "true"
  labels:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: event-listener-github
  name: github-listener
spec:
  port:
    targetPort: http-listener
  to:
    kind: Service
    name: event-listener-github
    weight: 100
  wildcardPolicy: None