apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: trigger-template-github
spec:
  params:
  - name: repo-url
  - name: revision
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: pipeline-
      namespace: tekton
    spec:
      pipelineRef:
        name: quarkus-ci
      params:
      - name: repo-url
        value: "$(tt.params.repo-url)"
      - name: revision
        value: "$(tt.params.revision)"
      workspaces:
      - name: source
        persistentVolumeClaim:
          claimName: source-pvc