apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: trigger-binding-quarkus-app
spec:
  params:
  - name: src
    value: .
  - name: image-name
    value: nexus3.nexus.svc.cluster.local/dborrego/workshop-tekton-argocd-app-quarkus
  - name: container-file
    value: src/main/docker/Dockerfile.jvm
  - name: skip-image-push
    value: "false"
  - name: repo-url
    value: http://gogs.gogs.svc.cluster.local:3000/gogs/app-quarkus.git