apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: github-push
spec:
  params:
  - name: revision
    value: "db062607f4f15ce6281957f07e57ded83003a2cc"
  - name: repo-url
    value: $(body.repository.clone_url)