apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nexus
  namespace: openshift-gitops
spec:
  destination:
    namespace: nexus
    server: "https://kubernetes.default.svc"
  source:
    path: dependencies/nexus
    repoURL: "https://github.com/dbgjerez/workshop-tekton-argocd"
    targetRevision: develop
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
