apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-operators
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-operators
    server: "https://kubernetes.default.svc"
  source:
    path: operator
    repoURL: "https://github.com/dbgjerez/workshop-tekton"
    targetRevision: develop
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
