apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: quarkus-ci
spec:
  workspaces:
    - name: source
  params:
    - name: url
      description: Git repository url
    - name: branch
      description: Revision to use
  tasks:
  - name: clone
    taskRef:
      name: git-clone
      kind: ClusterTask
    params:
      - name: url
        value: $(params.url)
      - name: revision
        value: $(params.revision)
      - name: deleteExisting
        value: 'true'
    workspaces:
      - name: output
        workspace: source