apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: quarkus-ci
spec:
  workspaces:
    - name: source
    - name: scratch
  params:
    - name: repo-url
      type: string
      description: Git repository url
    - name: revision
      type: string
      description: Revision to use
    - name: src
      type: string
      description: Source code folder
  tasks:
  - name: clone
    taskRef:
      name: git-clone
      kind: ClusterTask
    params:
      - name: url
        value: $(params.repo-url)
      - name: revision
        value: $(params.revision)
      - name: src
        value: $(params.src)
      - name: image-name
        value: $(params.image-name)
      - name: deleteExisting
        value: 'true'
    workspaces:
      - name: output
        workspace: source

  - name: test
    taskRef:
      name: maven
      kind: ClusterTask
    runAfter:
      - clone
    params:
      - name: MAVEN_IMAGE
        value: 'maven:3-openjdk-17'
      - name: GOALS
        value: ['clean', 'verify']
      - name: CONTEXT_DIR
        value: $(params.src)
    workspaces:
      - name: source
        workspace: source
      - name: maven-settings
        workspace: scratch

  - name: build
    taskRef:
      name: maven
      kind: ClusterTask
    runAfter:
      - test
    params:
      - name: MAVEN_IMAGE
        value: 'maven:3-openjdk-17'
      - name: CONTEXT_DIR
        value: $(params.src)
      - name: GOALS
        value: ['clean', 'package', '-DskipTests']
    workspaces:
      - name: source
        workspace: source
      - name: maven-settings
        workspace: scratch

  - name: build-image
    taskRef:
      name: buildah
      kind: ClusterTask
    runAfter:
      - build
    params:
      - name: IMAGE
        value: $(params.image-name)
      - name: DOCKERFILE
        value: $(params.container-file)
      - name: SKIP_PUSH
        vale: $(params.skip-image-push)
    workspaces:
      - name: source
        workspace: source