apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: quarkus-ci
spec:
  workspaces:
    - name: source
  params:
    - name: repo-url
      type: string
      description: Git repository url
    - name: revision
      type: string
      description: Revision to use
    - name: src
      type: string
      description: Source code folder
  tasks:
  - name: clone
    taskRef:
      name: git-clone
      kind: ClusterTask
    params:
      - name: url
        value: $(params.repo-url)
      - name: revision
        value: $(params.revision)
      - name: src
        value: $(params.src)
      - name: deleteExisting
        value: 'true'
    workspaces:
      - name: output
        workspace: source
      - name: maven-settings
        workspace: scratch

  - name: test
    taskRef:
      name: maven
      kind: ClusterTask
    runAfter:
      - clone
    params:
      - name: MAVEN_IMAGE
        value: 'maven:3-openjdk-11'
      - name: GOALS
        value: ['clean', 'verify']
      - name: CONTEXT_DIR
        value: $(params.src)
    workspaces:
      - name: source
        workspace: source