apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: quarkus-ci
spec:
  workspaces:
    - name: source
  params:
    - name: repo-url
      type: string
      description: Git repository url
    - name: revision
      type: string
      description: Revision to use
  tasks:
  - name: clone
    taskRef:
      name: git-clone
      kind: ClusterTask
    params:
      - name: repo-url
        value: $(params.repo-url)
      - name: revision
        value: $(params.revision)
      - name: deleteExisting
        value: 'true'
    workspaces:
      - name: output
        workspace: source