kind: Nexus
apiVersion: apps.m88i.io/v1alpha1
metadata:
  name: nexus3
  namespace: nexus
spec:
  networking:
    expose: false
  persistence:
    persistent: true
  replicas: 1
  resources:
    limits:
      cpu: '2'
      memory: 2Gi
    requests:
      cpu: '1'
      memory: 2Gi
  useRedHatImage: true
