apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-quarkus
  namespace: openshift-gitops
spec:
  destination:
    namespace: quarkus
    server: "https://kubernetes.default.svc"
  source:
    path: apps
    repoURL: "http://gogs.gogs.svc.cluster.local/gogs/app-quarkus-config.git"
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false