kind: Secret
apiVersion: v1
metadata:
  name: git-credentials
type: Opaque
stringData:
  .gitconfig: |
    [credential "http://gogs.gogs.svc.cluster.local:3000"]
      helper = store
    [user]
      email = dborrego@redhat.com
      name = David Borrego
  .git-credentials: |
    http://gogs:gogs@gogs.gogs.svc.cluster.local:3000