kind: ConfigMap
apiVersion: v1
metadata:
  name: gogs-config
  labels:
    app: gogs
data:
  app.ini: |
    RUN_MODE = prod
    RUN_USER = gogs
    [database]
    DB_TYPE  = postgres
    HOST     = gogs-postgresql:5432
    NAME     = gogs
    USER     = gogs
    PASSWD   = gogs
    [repository]
    ROOT = /opt/gogs/data/repositories
    [server]
    ROOT_URL=http://gogs-gogs.apps.cluster-js825.js825.sandbox763.opentlc.com
    SSH_DOMAIN=gogs-gogs.apps.cluster-js825.js825.sandbox763.opentlc.com
    [security]
    INSTALL_LOCK = true
    [service]
    ENABLE_CAPTCHA = false
    [webhook]
    SKIP_TLS_VERIFY = true