kind: Secret
apiVersion: v1
metadata:
  name: git-credentials
  namespace: tekton
type: Opaque
stringData:
  .gitconfig: |
    [credential "http://gogs.gogs.svc.cluster.local:3000"]
      helper = store
  .git-credentials: |
    http://gogs:gogs@gogs.gogs.svc.cluster.local:3000
    http://gogs:gogs@gogs.gogs.svc.cluster.local:3000/gogs/app-quarkus.git